### ISSUE TITLE
Allow to disable checking of MIME types when uploading submissions

### ISSUE THREAD

**Issue by hannesbraun** [hso-praktomat/praktomat#11]
The MIME type checks often do not add much but make life more complicated than necessary. There should be a way to switch them off. If a MIME type is unknown to the Praktomat, there is currently no way to upload such files, regardless of the MIME type filter.

**Comment by skogsbaer** [comment]
It would be ok for me if we removed this check completely.

**Comment by ifrh** [comment]
> , there is currently no way to upload such files, regardless of the MIME type filter.

Well that is not completly true: One can add "admin defined"  MIME-Types in settings/defaults-py
like here:

https://github.com/hso-praktomat/praktomat/blob/ae042a30d62d857240d8d198948ca35e26998bc8/src/settings/defaults.py#L429-L437
