### ISSUE TITLE
TEST_MAXFILESIZE should or could be usable together with USESAFEDOCKER

### ISSUE THREAD

**Issue by ifrh** [hso-praktomat/praktomat#14]
In README.md it is mentioned:

>   The maximum size of a file produced by a user submission (setting TEST_MAXFILESIZE, currently not supported with USESAFEDOCKER, until http://stackoverflow.com/questions/25789425 is resolved)

In http://stackoverflow.com/questions/25789425, which has been posted in Nov 2014, there exists an answer from the year 2015 points to a Docker Issue which has been closed as implemented for using ulimits. ( cf. https://github.com/KITPraktomatTeam/Praktomat/issues/358 )

**Comment by hannesbraun** [comment]
This should be already implemented:
https://github.com/hso-praktomat/praktomat/blob/ae042a30d62d857240d8d198948ca35e26998bc8/src/utilities/safeexec.py#L92-L93

Granted, I forgot to update the README...
