### ISSUE TITLE
Arguments for ScriptChecker

### ISSUE THREAD

**Issue by hannesbraun** [hso-praktomat/praktomat#3]
Having the ability to pass custom arguments to a ScriptChecker would be useful. This can be realized using a textfield in the admin view for a task. The arguments will be split by whitespace. Those extra arguments will be prepended to the currently existing filenames of the solution files which are also submitted as arguments.

**Comment by skogsbaer** [comment]
@hannesbraun this one gets more and more important. I have weird workarounds for extracting the exercise id from the task title. I would like to pass the exercise id via a commandline option.

**Comment by ifrh** [comment]
Well, just to mention a "work arround" . 
Use a CreateFileChecker to upload a text-file containing the "arguments" for a shellscript started via ScriptChecker.
(Of course that shellscript had to "read" the argument file :-) ) 
We used that way about 10 years ago, befor we switch to an own java based testframework.
