### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by rejahn** [hso-praktomat/praktomat#30]
I would like to see an improvement of README.md, with clear and updated instructions on how to run the praktomat locally. This way, more developers can help with the continuation of praktomat.  :)

**Comment by hannesbraun** [comment]
I know that the README is outdated in some places and some stuff is probably missing. For about the next month, I won't have time to work on this. If I've got time in August (or later), I'll see if I can improve the README. But I don't want to make any promises I can't keep ;)

For now though, there's also [praktomat-docker](https://github.com/hso-praktomat/praktomat-docker). This is our setup to actually run the Praktomat. At the same time, I'm using it for the development. Maybe that helps.

**Comment by rejahn** [comment]
I've been trying to use the [praktomat-docker](https://github.com/hso-praktomat/praktomat-docker) but when creating an instance the container for the `$COMPOSE_PROJECT_NAME_db` won't create after minutes. Do you have an idea what the problem could be?

![grafik](https://github.com/hso-praktomat/praktomat/assets/74012027/039c58e4-d980-4d85-8f5c-6a71493f40b8)

**Comment by hannesbraun** [comment]
That's definitely weird. I'd expect it to crash at least if something's misconfigured. Although I don't think that it should be related: did you create the "postgresql" directory in your home directory? (Unfortunately, that's not documented...)

https://github.com/hso-praktomat/praktomat-docker/blob/0c753f52ad36e2ece1fc345ff0a209801e07f909/docker-compose.yml#L39C18-L39C29

Other than that, it'd be purely guesswork from my side.
[However, I've read that if you've got low system entropy, that might be an issue.](https://stackoverflow.com/questions/59941911/docker-compose-up-hangs-forever-how-to-debug)
But again, I can't really tell, as I never had such an issue.

**Comment by skogsbaer** [comment]
@rejahn did you solve the problem? Seems like a docker/docker-compose problem to me. Otherwise, feel free to report bugs in the practomat-docker repo.

**Comment by rejahn** [comment]
> @rejahn did you solve the problem? Seems like a docker/docker-compose problem to me. Otherwise, feel free to report bugs in the practomat-docker repo.

the problem for me was the docker-compose file, where the init.sh file couldn't be found for some reason under $PWD/postgresql/init.sh. I could solve the problem using relative path.

Thank you!
