### ISSUE TITLE
safe-docker:latest  not found 

### ISSUE THREAD

**Issue by rejahn** [hso-praktomat/praktomat#31]
Praktomat unable to compile a helloworld.c.

![grafik](https://github.com/hso-praktomat/praktomat/assets/74012027/8f81bfa3-bfa0-4aa3-ba0b-af6b90fb9210)

`
Unable to find image 'safe-docker:latest' locally
docker: Error response from daemon: pull access denied for safe-docker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
`

I have checked my login after running `docker logout` and `docker login` and everything looks good. Maybe the `safe-docker` image not available anymore on [Docker Hub](https://hub.docker.com/)?

Here are the settings to compile the programm. With this setting we were able to test at our mutiple instances when using the praktomat code from [KIT](https://github.com/KITPraktomatTeam/Praktomat
)
![grafik](https://github.com/hso-praktomat/praktomat/assets/74012027/5dfeee07-b8ac-4c62-b6df-0eea2d24d9a1)

where `setup.exp`:

```## these variables are automatically generated by make ##
# Do not edit here. If you wish to override these values
# add them to the last section
# Set timeout, prompt, etc. 
set standard_timeout 1
set startup_timeout 10
set answer ""
set exit_cmd "0"
# change for praktomat to 
set spawn_program "../PROGRAM"
# uses this for linux
#set spawn_program "./build/quersumme"
## All variables above are generated by configure. Do Not Edit ##

# $Id: default.exp 901 2005-02-23 16:45:23Z stoerzer $

# This can be considered as the standard DejaGnu framework for usage
# in Praktomat.

#############################
# Don't change the following!
#############################

set timeout $standard_timeout
# If we haven't read the right prompt in PROGRAM_start, it doesn't
# make sense to do any other test.
set prompt_error 0
set prompt_input ""
# Load a program
proc PROGRAM_load { arg } {
    #
}

# Start program and wait for prompt
proc PROGRAM_start {prompt} {
    # it is impossible to use <pass> or <fail> in start :-(
    global standard_timeout
    global startup_timeout
    global timeout
    global prompt_input
    global spawn_id
    global prompt_error
    global spawn_program

    # Startup of the engine needs to much time.
    set timeout $startup_timeout
    spawn $spawn_program
    # Check for prompt
    set prompt_input $prompt
    expect {
	-re $prompt_input { }
	timeout { 
	    set prompt_error 1
	    send_user "\nFAIL: start "
	    send_user "(timeout with no prompt, expected \"$prompt_input\")\n"; 
	}
	eof {
	    set prompt_error 1
	    send_user "\nFAIL: start "
	    send_user "(no prompt, expected \"$prompt_input\")\n" 
	}
    }
    set timeout $standard_timeout
}

# End program
proc PROGRAM_exit {} {
}

# Own functions
proc PROGRAM_test {expr result} {
    PROGRAM_test_ "$expr" "$result" ""
}

proc PROGRAM_test_c {expr result comment} {
    PROGRAM_test_ "$expr" "$result" "\[$comment\]"
}

proc PROGRAM_test_ {expr result comment} {

    global answer
    global prompt_error
    global prompt_input

    # Don't continue if we haven't read the right prompt
    if $prompt_error {
	return
    }
    
    # Send expression and wait for echo
    if [catch {send "$expr\n"}] {
	send_user "\n"
	fail "could not send text, is the program running? $comment"
	return
    }

    # Quote the expected result
    regsub -all {[].$^()*+?|[]} $result {\\&} quoted
    # Quote the command
    regsub -all {[].$^()*+?|[]} $expr {\\&} cmd

    # Check result
    expect {
	-re "$cmd.*\[\r\n\].*$quoted" { 
	    send_user "\n"
	    pass "$expr $comment" 
	}
	eof {
 	    fail "$expr (got wrong answer, expected \"$result\") $comment" 
 	}
	-re "\[!\].*\[\r\n\]+$prompt_input" { 
	    send_user "\n"
 	    fail "$expr (got error, but expected \"$result\") $comment" 
 	}
	-ex "$prompt_input" {
	    send_user "\n"
	    fail "$expr (expected \"$result\") $comment" 
	}
	timeout { 
	    send_user "\n"
	    fail "$expr (timeout with no prompt, expected \"$prompt_input\") $comment"; 
	    expect "$prompt_input" 
	}
    }
    send_user "\n"
}

# Now go and start the program...
```

and the test `helloworld.exp`:

```
PROGRAM_start "Hello World!!"
PROGRAM_test "Hello World!!"
```

**Comment by rejahn** [comment]
@nomeata could you please get a look? :)

**Comment by nomeata** [comment]
I haven’t looked at these things in years, so I won't be of great help. I don’t think we used dockerhub back then (it may not have existed). Probably you have to manually add that container (or image?) to your local docker installation.

**Comment by hannesbraun** [comment]
From our side, there has never been a published image called `safe-docker`. That's just a placeholder name for whatever image you might want to use. For our purposes, we are using our own checker image (see the multi-checker in [hso-praktomat/praktomat-checkers](https://github.com/hso-praktomat/praktomat-checkers)). And I'm also not aware of a published image by the KIT.

Indeed, if you want to use the image corresponding to the Dockerfile (`docker-image/Dockerfile`) in this repository, you need to build that yourself.

Keep in mind, however, that we (Offenburg University) are only using the script checker as of now. Neither do we use other checkers, nor did we test the current state of the provided Dockerfile.

**Comment by rejahn** [comment]
that helps. Thank you @nomeata @hannesbraun  !
