### ISSUE TITLE
Deadline extension for individual students

### ISSUE THREAD

**Issue by hannesbraun** [hso-praktomat/praktomat#5]
Sometimes students are sick and need a deadline extension. These deadline extensions could be set through the admin interface of a task.

**Comment by skogsbaer** [comment]
@hannesbraun how much work is this?

**Comment by hannesbraun** [comment]
Probably somewhere around "medium". The most difficult part (for me) is determining how to properly modify the admin interface to add this configuration. Other than that, it should be mostly finding places in the code that depend on the deadline of a task and adjusting them accordingly.

**Comment by ifrh** [comment]
Do you mean, that it should be an extension inside the Task-Admin-Page  `/admin/tasks/task/$NUMBER/change/`
Or should it be an own Django-App Model with an own Admin-Page?

**Comment by hannesbraun** [comment]
What I had in mind was adding a kind of map to the task admin page `/admin/tasks/task/$NUMBER/change/` where you can add users/students that map to a timestamp/deadline. Students that are not added to that map would use the default deadline.
