### ISSUE TITLE
Do not show binary data in file view

### ISSUE THREAD

**Issue by hannesbraun** [hso-praktomat/praktomat#8]
Currently, Praktomat shows all files of a solution, even binary files. These should be filtered out.

See also https://github.com/KITPraktomatTeam/Praktomat/pull/332 for the original pull request I created to address this issue. I'll merge that soon into our fork.

**Comment by skogsbaer** [comment]
@hannesbraun that should be fixed now that we have our own repo

**Comment by hannesbraun** [comment]
Done! See merge commit de352f4ea94c00cfaf1b5df1d70398ad1569a867.
